name: Continous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  COMPILER_X86: gcc
  BUILD_DIR: ./build

jobs:
  tests:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/joseamador95/devcontainer:main
      credentials:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Config
      run: cmake -S . --preset default --fresh

    - name: Build Lib
      run: cmake --build --preset default -- -k 0

    - name: Unit Tests
      run: |
        cmake -S . --preset tests
        cmake --build --preset tests
        ctest --preset unittests

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ${{env.BUILD_DIR}}
